/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LayoutRouteImport } from './routes/_Layout'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LayoutSideBarSnoozeRouteImport } from './routes/_Layout/_SideBar/snooze'
import { Route as LayoutSideBarSentmailRouteImport } from './routes/_Layout/_SideBar/sentmail'
import { Route as LayoutSideBarDraftmailRouteImport } from './routes/_Layout/_SideBar/draftmail'
import { Route as LayoutSideBarComposeRouteImport } from './routes/_Layout/_SideBar/compose'
import { Route as LayoutNavBarUsersRouteImport } from './routes/_Layout/_NavBar/users'
import { Route as LayoutNavBarTagsRouteImport } from './routes/_Layout/_NavBar/tags'
import { Route as LayoutNavBarProjectsRouteImport } from './routes/_Layout/_NavBar/projects'
import { Route as LayoutNavBarFilesRouteImport } from './routes/_Layout/_NavBar/files'
import { Route as LayoutNavBarDashboardRouteImport } from './routes/_Layout/_NavBar/dashboard'
import { Route as LayoutNavBarCategoriesRouteImport } from './routes/_Layout/_NavBar/categories'
import { Route as LayoutNavBarUserIdUsersProfileRouteImport } from './routes/_Layout/_NavBar/$userId/users/profile'

const LayoutRoute = LayoutRouteImport.update({
  id: '/_Layout',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutSideBarSnoozeRoute = LayoutSideBarSnoozeRouteImport.update({
  id: '/_SideBar/snooze',
  path: '/snooze',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSideBarSentmailRoute = LayoutSideBarSentmailRouteImport.update({
  id: '/_SideBar/sentmail',
  path: '/sentmail',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSideBarDraftmailRoute = LayoutSideBarDraftmailRouteImport.update({
  id: '/_SideBar/draftmail',
  path: '/draftmail',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSideBarComposeRoute = LayoutSideBarComposeRouteImport.update({
  id: '/_SideBar/compose',
  path: '/compose',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutNavBarUsersRoute = LayoutNavBarUsersRouteImport.update({
  id: '/_NavBar/users',
  path: '/users',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutNavBarTagsRoute = LayoutNavBarTagsRouteImport.update({
  id: '/_NavBar/tags',
  path: '/tags',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutNavBarProjectsRoute = LayoutNavBarProjectsRouteImport.update({
  id: '/_NavBar/projects',
  path: '/projects',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutNavBarFilesRoute = LayoutNavBarFilesRouteImport.update({
  id: '/_NavBar/files',
  path: '/files',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutNavBarDashboardRoute = LayoutNavBarDashboardRouteImport.update({
  id: '/_NavBar/dashboard',
  path: '/dashboard',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutNavBarCategoriesRoute = LayoutNavBarCategoriesRouteImport.update({
  id: '/_NavBar/categories',
  path: '/categories',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutNavBarUserIdUsersProfileRoute =
  LayoutNavBarUserIdUsersProfileRouteImport.update({
    id: '/_NavBar/$userId/users/profile',
    path: '/$userId/users/profile',
    getParentRoute: () => LayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/categories': typeof LayoutNavBarCategoriesRoute
  '/dashboard': typeof LayoutNavBarDashboardRoute
  '/files': typeof LayoutNavBarFilesRoute
  '/projects': typeof LayoutNavBarProjectsRoute
  '/tags': typeof LayoutNavBarTagsRoute
  '/users': typeof LayoutNavBarUsersRoute
  '/compose': typeof LayoutSideBarComposeRoute
  '/draftmail': typeof LayoutSideBarDraftmailRoute
  '/sentmail': typeof LayoutSideBarSentmailRoute
  '/snooze': typeof LayoutSideBarSnoozeRoute
  '/$userId/users/profile': typeof LayoutNavBarUserIdUsersProfileRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/categories': typeof LayoutNavBarCategoriesRoute
  '/dashboard': typeof LayoutNavBarDashboardRoute
  '/files': typeof LayoutNavBarFilesRoute
  '/projects': typeof LayoutNavBarProjectsRoute
  '/tags': typeof LayoutNavBarTagsRoute
  '/users': typeof LayoutNavBarUsersRoute
  '/compose': typeof LayoutSideBarComposeRoute
  '/draftmail': typeof LayoutSideBarDraftmailRoute
  '/sentmail': typeof LayoutSideBarSentmailRoute
  '/snooze': typeof LayoutSideBarSnoozeRoute
  '/$userId/users/profile': typeof LayoutNavBarUserIdUsersProfileRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_Layout': typeof LayoutRouteWithChildren
  '/_Layout/_NavBar/categories': typeof LayoutNavBarCategoriesRoute
  '/_Layout/_NavBar/dashboard': typeof LayoutNavBarDashboardRoute
  '/_Layout/_NavBar/files': typeof LayoutNavBarFilesRoute
  '/_Layout/_NavBar/projects': typeof LayoutNavBarProjectsRoute
  '/_Layout/_NavBar/tags': typeof LayoutNavBarTagsRoute
  '/_Layout/_NavBar/users': typeof LayoutNavBarUsersRoute
  '/_Layout/_SideBar/compose': typeof LayoutSideBarComposeRoute
  '/_Layout/_SideBar/draftmail': typeof LayoutSideBarDraftmailRoute
  '/_Layout/_SideBar/sentmail': typeof LayoutSideBarSentmailRoute
  '/_Layout/_SideBar/snooze': typeof LayoutSideBarSnoozeRoute
  '/_Layout/_NavBar/$userId/users/profile': typeof LayoutNavBarUserIdUsersProfileRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/categories'
    | '/dashboard'
    | '/files'
    | '/projects'
    | '/tags'
    | '/users'
    | '/compose'
    | '/draftmail'
    | '/sentmail'
    | '/snooze'
    | '/$userId/users/profile'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/categories'
    | '/dashboard'
    | '/files'
    | '/projects'
    | '/tags'
    | '/users'
    | '/compose'
    | '/draftmail'
    | '/sentmail'
    | '/snooze'
    | '/$userId/users/profile'
  id:
    | '__root__'
    | '/'
    | '/_Layout'
    | '/_Layout/_NavBar/categories'
    | '/_Layout/_NavBar/dashboard'
    | '/_Layout/_NavBar/files'
    | '/_Layout/_NavBar/projects'
    | '/_Layout/_NavBar/tags'
    | '/_Layout/_NavBar/users'
    | '/_Layout/_SideBar/compose'
    | '/_Layout/_SideBar/draftmail'
    | '/_Layout/_SideBar/sentmail'
    | '/_Layout/_SideBar/snooze'
    | '/_Layout/_NavBar/$userId/users/profile'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LayoutRoute: typeof LayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_Layout': {
      id: '/_Layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_Layout/_SideBar/snooze': {
      id: '/_Layout/_SideBar/snooze'
      path: '/snooze'
      fullPath: '/snooze'
      preLoaderRoute: typeof LayoutSideBarSnoozeRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_Layout/_SideBar/sentmail': {
      id: '/_Layout/_SideBar/sentmail'
      path: '/sentmail'
      fullPath: '/sentmail'
      preLoaderRoute: typeof LayoutSideBarSentmailRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_Layout/_SideBar/draftmail': {
      id: '/_Layout/_SideBar/draftmail'
      path: '/draftmail'
      fullPath: '/draftmail'
      preLoaderRoute: typeof LayoutSideBarDraftmailRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_Layout/_SideBar/compose': {
      id: '/_Layout/_SideBar/compose'
      path: '/compose'
      fullPath: '/compose'
      preLoaderRoute: typeof LayoutSideBarComposeRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_Layout/_NavBar/users': {
      id: '/_Layout/_NavBar/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof LayoutNavBarUsersRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_Layout/_NavBar/tags': {
      id: '/_Layout/_NavBar/tags'
      path: '/tags'
      fullPath: '/tags'
      preLoaderRoute: typeof LayoutNavBarTagsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_Layout/_NavBar/projects': {
      id: '/_Layout/_NavBar/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof LayoutNavBarProjectsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_Layout/_NavBar/files': {
      id: '/_Layout/_NavBar/files'
      path: '/files'
      fullPath: '/files'
      preLoaderRoute: typeof LayoutNavBarFilesRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_Layout/_NavBar/dashboard': {
      id: '/_Layout/_NavBar/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof LayoutNavBarDashboardRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_Layout/_NavBar/categories': {
      id: '/_Layout/_NavBar/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof LayoutNavBarCategoriesRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_Layout/_NavBar/$userId/users/profile': {
      id: '/_Layout/_NavBar/$userId/users/profile'
      path: '/$userId/users/profile'
      fullPath: '/$userId/users/profile'
      preLoaderRoute: typeof LayoutNavBarUserIdUsersProfileRouteImport
      parentRoute: typeof LayoutRoute
    }
  }
}

interface LayoutRouteChildren {
  LayoutNavBarCategoriesRoute: typeof LayoutNavBarCategoriesRoute
  LayoutNavBarDashboardRoute: typeof LayoutNavBarDashboardRoute
  LayoutNavBarFilesRoute: typeof LayoutNavBarFilesRoute
  LayoutNavBarProjectsRoute: typeof LayoutNavBarProjectsRoute
  LayoutNavBarTagsRoute: typeof LayoutNavBarTagsRoute
  LayoutNavBarUsersRoute: typeof LayoutNavBarUsersRoute
  LayoutSideBarComposeRoute: typeof LayoutSideBarComposeRoute
  LayoutSideBarDraftmailRoute: typeof LayoutSideBarDraftmailRoute
  LayoutSideBarSentmailRoute: typeof LayoutSideBarSentmailRoute
  LayoutSideBarSnoozeRoute: typeof LayoutSideBarSnoozeRoute
  LayoutNavBarUserIdUsersProfileRoute: typeof LayoutNavBarUserIdUsersProfileRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutNavBarCategoriesRoute: LayoutNavBarCategoriesRoute,
  LayoutNavBarDashboardRoute: LayoutNavBarDashboardRoute,
  LayoutNavBarFilesRoute: LayoutNavBarFilesRoute,
  LayoutNavBarProjectsRoute: LayoutNavBarProjectsRoute,
  LayoutNavBarTagsRoute: LayoutNavBarTagsRoute,
  LayoutNavBarUsersRoute: LayoutNavBarUsersRoute,
  LayoutSideBarComposeRoute: LayoutSideBarComposeRoute,
  LayoutSideBarDraftmailRoute: LayoutSideBarDraftmailRoute,
  LayoutSideBarSentmailRoute: LayoutSideBarSentmailRoute,
  LayoutSideBarSnoozeRoute: LayoutSideBarSnoozeRoute,
  LayoutNavBarUserIdUsersProfileRoute: LayoutNavBarUserIdUsersProfileRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LayoutRoute: LayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
